receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  jaeger:
    #    endpoint: "host.docker.internal:30003"
    tls:
      insecure: true
  logging:
  prometheus:
    endpoint: "otelcol:9464"
  tanzuobservability:
    traces:
      endpoint: "http://wavefrontproxy:30001"
    metrics:
      endpoint: "http://wavefrontproxy:2878"


processors:
  batch:

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, tanzuobservability]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [tanzuobservability, logging]
